import { FormEvent, useMemo, useState } from 'react';
import { ArrowRight, Check, ChevronDown, LayoutGrid, Menu, MessageCircle, Search, ShoppingBag, Sparkles, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { paymentUrl } from '@/lib/payment';
import { hostingPlans } from '@/lib/hostingPlans';

type Category = 'All' | 'Launch' | 'VPN';
export const hostingCategories: Category[] = ['All', 'Launch', 'VPN'];

const Hosting = () => {
  const [category, setCategory] = useState<Category>('All');
  const [query, setQuery] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const [email, setEmail] = useState('');
  const [leadState, setLeadState] = useState<'idle' | 'sending' | 'success' | 'error'>('idle');
  const [chatOpen, setChatOpen] = useState(false);
  const [chatInput, setChatInput] = useState('');
  const [chatMessages, setChatMessages] = useState([{ from: 'support', text: 'Hi. Ask about plans, AWS Ubuntu OpenVPN setup, or checkout.' }]);
  const launchPlan = hostingPlans.find((plan) => plan.badge === 'Launch') ?? hostingPlans[0];
  const visiblePlans = useMemo(() => hostingPlans.filter((plan) => {
    const matchesCategory = category === 'All' || plan.badge === category;
    const matchesQuery = !query || `${plan.name} ${plan.tagline} ${plan.description}`.toLowerCase().includes(query.toLowerCase());
    return matchesCategory && matchesQuery;
  }), [category, query]);
  const purchasePlan = (stripeUrl?: string) => {
    if (stripeUrl) { window.location.assign(paymentUrl); return; }
    window.location.href = 'mailto:support@tingi.host?subject=Free%20hosting%20request';
  };
  const submitLead = async (event: FormEvent) => {
    event.preventDefault(); setLeadState('sending');
    try {
      const response = await fetch('/api/leads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) });
      if (!response.ok) throw new Error('Unable to subscribe');
      setLeadState('success'); setEmail('');
    } catch { setLeadState('error'); }
  };
  const sendChatMessage = (text = chatInput) => {
    const trimmedText = text.trim();
    if (!trimmedText) return;
    setChatMessages((messages) => [...messages, { from: 'visitor', text: trimmedText }, { from: 'support', text: 'Thanks. A support reply will follow by email. For urgent account issues, contact support directly.' }]);
    setChatInput('');
  };
  return (
    <main className="storefront storefront-dark">
      <div className="announcement announcement-dark"><Sparkles size={13} /> Swiss-hosted privacy infrastructure, independent from Proton <ArrowRight size={13} /></div>
      <header className="store-header store-header-dark">
        <div className="hosting-brand-group"><Link className="hosting-home-link" to="/">Back to home</Link><a className="brand" href="#top"><span className="brand-mark">T</span>Tingi Hosting</a></div>
        <nav className={menuOpen ? 'main-nav open' : 'main-nav'}>
          <a href="#plans" onClick={() => setMenuOpen(false)}>Plans</a>
          <a href="#buying-guide" onClick={() => setMenuOpen(false)}>Buying guide</a>
          <a href="#proton-guide" onClick={() => setMenuOpen(false)}>Proton guide</a>
          <a href="#data-safety" onClick={() => setMenuOpen(false)}>Data safety</a>
          <a href="#secure-access" onClick={() => setMenuOpen(false)}>Safe access</a>
          <a href="#safety-guide" onClick={() => setMenuOpen(false)}>Safety guide</a>
          <a href="#why" onClick={() => setMenuOpen(false)}>Why hosting</a>
          <a href="#support" onClick={() => setMenuOpen(false)}>Get updates</a>
        </nav>
        <div className="header-actions">
          <button className="icon-button" aria-label="Focus search" onClick={() => document.getElementById('search')?.focus()}><Search size={18} /></button>
          <button className="bag-button" onClick={() => purchasePlan(launchPlan.stripeUrl)}><ShoppingBag size={17} /><span>Start for $12/mo</span></button>
          <button className="menu-button" aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
      </header>
      <section className="hero" id="top">
        <div className="hero-copy">
          <p className="eyebrow">Swiss-hosted infrastructure for privacy-focused projects</p>
          <h1>Hosting for onion sites,<br /><em>guides, and tutorials.</em></h1>
          <p className="hero-text">Tingi helps you plan, launch, and maintain privacy-focused websites, lawful .onion services, and security tutorials on Swiss-hosted infrastructure independent from Proton.</p>
          <div className="hero-actions"><button className="button button-dark" onClick={() => purchasePlan(launchPlan.stripeUrl)}>Start hosting for $12/mo <ArrowRight size={16} /></button><a className="text-link" href="#plans">Compare plans <ArrowRight size={15} /></a></div>
          <div className="hero-note"><span className="avatar-stack"><i>J</i><i>M</i><i>A</i></span><span>Trusted by founders, agencies, and growth teams</span></div>
        </div>
        <div className="hero-art"><div className="art-orbit orbit-one" /><div className="art-orbit orbit-two" /><div className="art-window"><div className="window-top"><span /><span /><span /></div><div className="window-lines"><b /><b /><b /><b /></div><div className="window-chip">99.9% UPTIME</div></div><div className="art-sticker sticker-one">FAST<br /><strong>HOSTING</strong></div><div className="art-sticker sticker-two">✦</div></div>
      </section>
      <section className="value-strip value-strip-dark"><div><strong>Swiss-hosted</strong><span>Infrastructure located in Switzerland and operated independently from Proton.</span></div><div><strong>99.9% uptime</strong><span>Performance-first hosting for businesses that cannot afford downtime.</span></div><div><strong>Private support</strong><span>Monitoring, security, and tutorials without the usual noise.</span></div></section>
      <section className="collection" id="plans">
        <div className="section-heading"><div><p className="eyebrow">Hosting plans</p><h2>Pick a plan<br /><em>that fits your pace.</em></h2></div><p>Every plan includes regular backups, monitoring, and a clean path for onion services, educational guides, and growing privacy projects.</p></div>
        <div className="shop-toolbar"><div className="filters">{hostingCategories.map((item) => <button className={category === item ? 'filter active' : 'filter'} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><label className="search-field"><Search size={16} /><input id="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search plans" /><ChevronDown size={15} /></label></div>
        <div className="product-grid">{visiblePlans.map((plan) => <article className="product-card" key={plan.name}><div className={`product-visual ${plan.color}`}><span className="product-symbol">⌁</span>{plan.featured && <span className="featured-tag">Most popular</span>}<div className="visual-grid" /></div><div className="product-info"><div><p className="product-category">{plan.badge}</p><h3>{plan.name}</h3></div><span className="price">{plan.price}<small>{plan.period}</small></span></div><p className="product-description">{plan.description}</p><div className="product-footer"><span className="product-detail"><Check size={14} /> {plan.tagline}</span><button className="add-button" aria-label={`Buy ${plan.name}`} onClick={() => purchasePlan(plan.stripeUrl)}><ShoppingBag size={16} /></button></div></article>)}</div>
      </section>
      <section className="buying-guide" id="buying-guide"><div className="section-heading"><div><p className="eyebrow">How to buy</p><h2>Choose a plan,<br /><em>keep your keys private.</em></h2></div><p>Use the secure checkout link for your plan. Tingi will never ask for a wallet private key, seed phrase, password, or secret token.</p></div><div className="guide-grid"><article className="guide-step"><span>01</span><h3>Choose a plan</h3><p>Open Plans, compare the features, and select the hosting tier that fits your site or lawful onion service.</p></article><article className="guide-step"><span>02</span><h3>Open checkout</h3><p>Select Choose plan or Buy now. You will be sent to the configured payment provider to complete your purchase.</p></article><article className="guide-step"><span>03</span><h3>Confirm access</h3><p>Keep your order confirmation and follow the onboarding instructions. Only share public wallet addresses when a supported payment method requires one.</p></article></div><div className="key-warning"><strong>Security rule:</strong> never paste a private key, seed phrase, recovery phrase, password, or API secret into a checkout form or support chat. If a payment needs a key, use only the provider's official signing prompt and verify the domain first.</div></section>
      <section className="vpn-guide" id="vpn-guide"><div className="section-heading"><div><p className="eyebrow">AWS Ubuntu OpenVPN guide</p><h2>Build your tunnel,<br /><em>lock it down.</em></h2></div><p>A practical setup path for your own AWS EC2 server. Use an isolated account, restrict access, and keep client profiles private.</p></div><div className="vpn-steps"><article><span>01</span><h3>Launch Ubuntu on EC2</h3><p>Create an Ubuntu LTS instance, assign an Elastic IP, and use a dedicated key pair. Keep the SSH rule limited to your own IP address.</p></article><article><span>02</span><h3>Set the security group</h3><p>Allow SSH only from your administration IP and allow the VPN port you choose, commonly UDP 1194. Do not expose the admin panel publicly.</p></article><article><span>03</span><h3>Install and update</h3><p>Apply Ubuntu updates first, then install OpenVPN from a trusted official package or maintained deployment guide. Remove unused services.</p></article><article><span>04</span><h3>Create client profiles</h3><p>Generate one profile per device, test from a separate network, and revoke individual profiles when a device is lost or replaced.</p></article><article><span>05</span><h3>Maintain the server</h3><p>Monitor login activity, review security-group rules, rotate credentials, back up configuration securely, and patch the instance regularly.</p></article></div><div className="key-warning"><strong>Never publish client profiles or private keys.</strong> Store `.ovpn` files securely, use MFA wherever AWS supports it, and keep recovery material offline.</div></section>
      <section className="proton-guide" id="proton-guide"><div className="section-heading"><div><p className="eyebrow">Proton VPN guide</p><h2>Connect privately,<br /><em>check every setting.</em></h2></div><p>Use Proton VPN through its official app for everyday privacy. Proton VPN is separate from your AWS Ubuntu OpenVPN server and should not be treated as the same connection.</p></div><div className="proton-steps"><article><span>01</span><h3>Install the official app</h3><p>Download Proton VPN only from Proton's official website or your device's trusted app store, then sign in without sharing your password.</p></article><article><span>02</span><h3>Use Quick Connect</h3><p>Start with Quick Connect, or choose a nearby server when you need a specific region. Avoid unknown configuration files.</p></article><article><span>03</span><h3>Enable protection</h3><p>Turn on the kill switch and auto-connect options that fit your device, especially when using public Wi-Fi.</p></article><article><span>04</span><h3>Verify the connection</h3><p>Check your public IP and DNS status using a reputable test page, and confirm the Proton app shows an active connection.</p></article><article><span>05</span><h3>Know which VPN is active</h3><p>Disconnect one VPN before starting another. Running Proton and your AWS OpenVPN tunnel together can create routing conflicts.</p></article></div></section>
      <section className="data-safety" id="data-safety"><div className="section-heading"><div><p className="eyebrow">Data safety</p><h2>Your data is not<br /><em>a product.</em></h2></div><p>We aim to collect only what is needed to provide hosting, support, billing, and security. Privacy still has limits, so read the policy that applies to your service.</p></div><div className="data-safety-grid"><article><span>01</span><h3>Collect less</h3><p>Keep account, billing, support, and security records separate. Do not send private keys, seed phrases, or unnecessary personal details through chat.</p></article><article><span>02</span><h3>Third-party requests</h3><p>We do not casually hand over customer information. Requests are reviewed, scoped to data we actually hold, and challenged where the law allows.</p></article><article><span>03</span><h3>Valid legal process</h3><p>We comply with binding legal obligations. We provide only the information legally required and notify customers when notification is permitted.</p></article><article><span>04</span><h3>Be clear about limits</h3><p>No provider can promise perfect anonymity or immunity from lawful process. Use strong account security and keep sensitive material off hosted systems.</p></article></div><div className="data-safety-note"><strong>Plain English:</strong> third parties do not get a free pass to customer data. We review requests, protect what we can, and communicate honestly about what we must do.</div></section>
      <section className="secure-access-guide" id="secure-access"><div className="section-heading"><div><p className="eyebrow">Safe onion-site access</p><h2>Use a setup<br /><em>you understand.</em></h2></div><p>For lawful research and privacy education, choose tools that match your threat model. No operating system or browser guarantees perfect anonymity.</p></div><div className="secure-access-grid"><article><span>01</span><h3>Start with Tor Browser</h3><p>Download it only from the official Tor Project, verify the download when practical, and keep the browser at its default privacy settings.</p></article><article><span>02</span><h3>Use Tails for a temporary session</h3><p>Boot Tails from official installation media for work that should not remain on the local computer. Keep files out of persistent storage unless you need them.</p></article><article><span>03</span><h3>Use Qubes for isolation</h3><p>Separate activities into different qubes, keep personal and research identities apart, and treat downloaded files as untrusted until scanned.</p></article><article><span>04</span><h3>Verify before connecting</h3><p>Get onion addresses from official sources, check spelling carefully, and avoid links from unsolicited messages or suspicious directories.</p></article><article><span>05</span><h3>Protect your identity</h3><p>Do not sign into personal accounts, reuse usernames, reveal location details, or upload identifying photos while using a privacy-focused workspace.</p></article></div><div className="key-warning"><strong>Safety limit:</strong> Tails, Qubes, Tor, and VPNs reduce some risks but cannot protect you from scams, malware, compromised accounts, or mistakes. Keep systems updated and follow local law.</div></section>
      <section className="safety-guide" id="safety-guide"><div className="section-heading"><div><p className="eyebrow">Dark-web safety guide</p><h2>Privacy starts with<br /><em>good habits.</em></h2></div><p>Use these defensive basics for lawful research, publishing, and privacy-focused work. No service can remove every risk.</p></div><div className="safety-grid"><article><span>01</span><h3>Protect your identity</h3><p>Use a separate profile and avoid mixing personal names, accounts, photos, or identifying details with privacy-focused activity.</p></article><article><span>02</span><h3>Verify every address</h3><p>Get onion addresses from trusted official sources, check them carefully, and treat unexpected links or urgent messages as phishing attempts.</p></article><article><span>03</span><h3>Keep software current</h3><p>Download Tor Browser and security tools only from official sources, keep them updated, and avoid unknown extensions or files.</p></article><article><span>04</span><h3>Handle payments safely</h3><p>Use the official checkout domain. Never share private keys, seed phrases, passwords, recovery codes, or API secrets.</p></article></div></section>
      <section className="story" id="why"><div className="story-mark"><LayoutGrid size={27} /></div><div><p className="eyebrow">Why brands choose Tingi</p><h2>Simple hosting,<br /><em>serious performance.</em></h2><p>We combine resilient infrastructure, live monitoring, and practical tutorials so your public site or lawful onion service stays stable, protected, and easier to manage.</p><div className="promise-list"><span><Check size={15} /> Managed hosting with daily backups</span><span><Check size={15} /> Free SSL, CDN, and security hardening</span><span><Check size={15} /> Direct support for launches and upgrades</span></div></div></section>
      <section className="newsletter" id="support"><p className="eyebrow">A helpful first step</p><h2>Get the next hosting update.</h2><p>One short email with launch offers, onion-site setup guidance, and practical security tutorials. No clutter.</p><form className="email-form" onSubmit={submitLead}><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" aria-label="Email address" required /><button className="button button-dark" disabled={leadState === 'sending'}>{leadState === 'sending' ? 'Joining...' : 'Join free'} <ArrowRight size={16} /></button></form>{leadState === 'success' && <p className="form-message">You’re on the list. Watch your inbox for launch updates.</p>}{leadState === 'error' && <p className="form-message">We couldn’t sign you up right now. Please try again.</p>}</section>
      <footer><div className="hosting-footer-brand"><Link className="hosting-home-link" to="/">Back to home</Link><a className="brand" href="#top"><span className="brand-mark">T</span>Tingi Hosting</a></div><span>Privacy-focused infrastructure for sites, onion services, and tutorials.</span><div><a href="#plans">Plans</a><a href="#buying-guide">Buying guide</a><a href="#vpn-guide">VPN setup</a><a href="#proton-guide">Proton guide</a><a href="#data-safety">Data safety</a><a href="#secure-access">Safe access</a><a href="#safety-guide">Safety</a><a href="#why">Why us</a><a href="#support">Updates</a></div></footer>
      {chatOpen && <section className="support-chat" aria-label="Support chat"><div className="support-chat-header"><div><strong>Tingi support</strong><span>Usually replies by email</span></div><button type="button" onClick={() => setChatOpen(false)} aria-label="Close support chat"><X size={17} /></button></div><div className="support-chat-messages">{chatMessages.map((message, index) => <p className={`support-message ${message.from}`} key={`${message.from}-${index}`}>{message.text}</p>)}</div><div className="support-quick-actions"><button type="button" onClick={() => sendChatMessage('Which plan should I choose?')}>Plan help</button><button type="button" onClick={() => sendChatMessage('I need AWS Ubuntu OpenVPN help.')}>VPN setup</button></div><form className="support-chat-form" onSubmit={(event) => { event.preventDefault(); sendChatMessage(); }}><input value={chatInput} onChange={(event) => setChatInput(event.target.value)} placeholder="Type a question" aria-label="Support message" /><button type="submit" aria-label="Send support message"><ArrowRight size={16} /></button></form><a className="support-email-link" href="mailto:support@tingi.host">Email support directly</a></section>}
      <button className="support-chat-launcher" type="button" onClick={() => setChatOpen((open) => !open)} aria-label="Open support chat"><MessageCircle size={20} /> <span>Support</span></button>
    </main>
  );
};

export default Hosting;
