server {
    listen 80;
    listen [::]:80;
    server_name hosting.onemedia.asia;
    root /var/www/hosting.onemedia.asia/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name panel.onemedia.asia;
    root /var/www/panel.onemedia.asia/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
